spring:
  application:
    name: hello-spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management: # 2.8 是没有这段配置的
  metrics:
    web:
      server:
        auto-time-requests: false