spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/